// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "FuradWho",
            "email": "liu1337543811@gmail.com"
        },
        "license": {
            "name": "Fabric 2.3.3",
            "url": "https://hyperledger-fabric.readthedocs.io/zh_CN/release-2.2/who_we_are.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/LifeCycleChaincodeTest": {
            "get": {
                "description": "LifeCycleChaincodeTest-操作测试接口",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试接口"
                ],
                "summary": "操作测试接口",
                "responses": {
                    "200": {
                        "description": "{ \"code\": 200, \"msg\": \"connection success\" }",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "{ \" \" }",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/Test": {
            "get": {
                "description": "Test-网络连通性测试",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试接口"
                ],
                "summary": "网络连通性测试",
                "responses": {
                    "200": {
                        "description": "{ \"code\": 200, \"msg\": \"connection success\" }",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "{ \" \" }",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/cc/ApproveCC": {
            "post": {
                "description": "ApproveCC-请求当前组织批准链码",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "链码操作"
                ],
                "summary": "请求当前组织批准链码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所在组织的用户名",
                        "name": "UserName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码所在的组织",
                        "name": "Org",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码所在的节点",
                        "name": "Peer",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码所在的通道",
                        "name": "ChannelId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求排序节点",
                        "name": "Orderer",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码ID(名称)",
                        "name": "ChaincodeId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码包ID",
                        "name": "PackageId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码版本",
                        "name": "Version",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码更新次数",
                        "name": "Sequence",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \"code\": 200, \"msg\": \"success\",\"data\": {\"txId\":\"\"} }",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "{ \"code\": 400, \"msg\": \"Failed to approve the chaincode \",\"data\": \"\" }",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/cc/CommitCC": {
            "post": {
                "description": "CommitCC-提交已通过MSP认证的链码",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "链码操作"
                ],
                "summary": "提交已通过MSP认证的链码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所在组织的用户名",
                        "name": "user_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码所在的组织",
                        "name": "org",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码所在的节点",
                        "name": "peer",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码所在的通道",
                        "name": "channel_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求排序节点",
                        "name": "orderer",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码ID(名称)",
                        "name": "chaincode_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码版本",
                        "name": "version",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码更新次数",
                        "name": "sequence",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \"code\": 200, \"msg\": \"success\",\"data\": {\"txId\":\"\"} }",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "{ \"code\": 400, \"msg\": \"Failed to CommitCC \",\"data\": \"\" }",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/cc/InstallCC": {
            "post": {
                "description": "InstallCC-安装链码",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "链码操作"
                ],
                "summary": "安装链码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所在组织的用户名",
                        "name": "UserName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "安装链码所在的组织",
                        "name": "Org",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码ID(名称)",
                        "name": "ChaincodeId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "安装链码所在的节点",
                        "name": "Peer",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \"code\": 200, \"msg\": \"success\",\"data\": {\"txId\":\"\"} }",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "{ \"code\": 400, \"msg\": \"The chaincode has installed \",\"data\": \"\" }",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/cc/QueryApprovedCC": {
            "post": {
                "description": "QueryApprovedCC-查询是否通过当前组织批准链码",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "链码操作"
                ],
                "summary": "查询是否通过当前组织批准链码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所在组织的用户名",
                        "name": "UserName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码所在的组织",
                        "name": "Org",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码所在的节点",
                        "name": "Peer",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码所在的通道",
                        "name": "ChannelId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码ID(名称)",
                        "name": "ChaincodeId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码更新次数",
                        "name": "Sequence",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \"code\": 200, \"msg\": \"success\",\"data\": {\"packageId\":\"\"} }",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "{ \"code\": 400, \"msg\": \"Failed to QueryApprovedCC the chaincode \",\"data\": \"\" }",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/cc/QueryInstalled": {
            "post": {
                "description": "QueryInstalled-请求当前节点安装的链码",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "链码操作"
                ],
                "summary": "请求当前节点安装的链码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所在组织的用户名",
                        "name": "UserName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码所在的组织",
                        "name": "Org",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码所在的节点",
                        "name": "Peer",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \"code\": 200, \"msg\": \"success\",\"data\": {\"chaincodes\":[]} }",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "{ \"code\": 400, \"msg\": \"Failed to QueryInstalled chaincode\",\"data\": \"\" }",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/cc/RequestApproveCCByOther": {
            "post": {
                "description": "RequestApproveCCByOther-请求其他组织批准链码",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "链码操作"
                ],
                "summary": "请求其他组织批准链码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链码所在的组织",
                        "name": "Org",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码所在的节点",
                        "name": "Peer",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码所在的通道",
                        "name": "ChannelId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求排序节点",
                        "name": "Orderer",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码ID(名称)",
                        "name": "ChaincodeId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码包ID",
                        "name": "PackageId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码版本",
                        "name": "Version",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码更新次数",
                        "name": "Sequence",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \"code\": 200, \"msg\": \"success\",\"data\": {\"txId\":\"\"} }",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "{ \"code\": 400, \"msg\": \"Failed to RequestApproveCCByOther the chaincode \",\"data\": \"\" }",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/cc/RequestInstallCCByOther": {
            "post": {
                "description": "RequestInstallCCByOther-请求其他组织安装链码",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "链码操作"
                ],
                "summary": "请求其他组织安装链码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "链码所在的组织",
                        "name": "Org",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码所在的节点",
                        "name": "Peer",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "链码ID(名称)",
                        "name": "ChaincodeId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \"code\": 200, \"msg\": \"success\",\"data\": {\"txId\":\"\"} }",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "{ \"code\": 400, \"msg\": \"Failed to RequestInstallCCByOther \",\"data\": \"\" }",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/channel/CreateChannel": {
            "post": {
                "description": "CreateChannel-创建通道",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户通道操作"
                ],
                "summary": "创建通道",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所在组织的用户名",
                        "name": "UserName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "安装链码所在的组织",
                        "name": "OrgName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "创建通道名称",
                        "name": "ChannelId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "排序节点",
                        "name": "Orderer",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \"code\": 200, \"msg\": \"success\",\"data\": {\"txId\":\"\"} }",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "{ \"code\": 400, \"msg\": \"Failed to create channel\",\"data\": \"\" }",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/channel/GetNetworkConfig": {
            "get": {
                "description": "GetNetworkConfig-获取\"网络通道组织节点\"信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "网络通道操作"
                ],
                "summary": "获取网络信息",
                "responses": {
                    "200": {
                        "description": "{ \"code\": 200, \"msg\": \"success\",\"data\": {} }",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "{ \"code\": 400, \"msg\": \"Failed to GetNetworkConfig \",\"data\": \"\" }",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/channel/GetOrgTargetPeers": {
            "get": {
                "description": "GetOrgTargetPeers-获取组织节点信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "网络通道操作"
                ],
                "summary": "获取组织节点信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所在组织名",
                        "name": "org",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \"code\": 200, \"msg\": \"success\",\"data\": {\"peers\":[]} }",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "{ \"code\": 400, \"msg\": \"Failed to GetOrgTargetPeers \",\"data\": \"\" }",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/channel/JoinChannel": {
            "post": {
                "description": "JoinChannel-加入当前通道",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户通道操作"
                ],
                "summary": "加入当前通道",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所在组织的用户名",
                        "name": "UserName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "安装链码所在的组织",
                        "name": "OrgName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "创建通道名称",
                        "name": "ChannelId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \"code\": 200, \"msg\": \"success\",\"data\": {\"success to join channel\"} }",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "{ \"code\": 400, \"msg\": \"Failed to join channel\",\"data\": \"\" }",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/user/CreateUser": {
            "post": {
                "description": "CreateUser-创建用户",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户通道操作"
                ],
                "summary": "创建用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所在组织的用户名",
                        "name": "UserName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "所在组织的用户密码",
                        "name": "Secret",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户类型",
                        "name": "UserType",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "安装链码所在的组织",
                        "name": "OrgName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "所申请组织的CA服务器",
                        "name": "CaName",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \"code\": 200, \"msg\": \"success\",\"data\": { \"PriFile\": priFile, \"PubFile\" : pubFile }}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "{ \"code\": 400, \"msg\": \"Field to CreateUser\",\"data\": \"\" }",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:9099",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "GO Fabric 对于Fabric网络的操作",
	Description: "go sdk for Fabric",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
